declare module "*.png";
declare module "*./Makingtab.module.css";
declare module "*./Banner.module.css";
declare module "*../ModuleCSS/pokemon.module.css";
declare module "*../ModuleCSS/onepiece.module.css";
declare module "*../ModuleCSS/dragonball.module.css";
declare module "*../ModuleCSS/vice.module.css";
declare module "*../ModuleCSS/unionarena.module.css";
declare module "*../ModuleCSS/others.module.css";
declare module "*../Header/PagesChangetag.module.css";
declare module "*./Loadingdots.module.css";
declare module "*../Loading/Loadingdots.module.css";
declare module "*../Loading/Loadingsquares.module.css";
declare module "*../../Header/Navigatedp/Gachadp.module.css"
