declare module "*.png";
declare module "*./Makingtab.module.css";
declare module "*./Banner.module.css";
declare module "*../ModuleCSS/pokemon.module.css";
declare module "*../ModuleCSS/onepiece.module.css";
declare module "*../ModuleCSS/dragonball.module.css";
declare module "*../ModuleCSS/vice.module.css";
declare module "*../ModuleCSS/unionarena.module.css";
declare module "*../ModuleCSS/others.module.css"
